import type { CodexUsageStatsSnapshot } from "./desktop-types";
import { state } from "./app-runtime";

export function createPreviewCodexUsageStats(): CodexUsageStatsSnapshot {
  const updatedAt = new Date().toISOString();
  return {
    updatedAt,
    filter: state.usageStatsFilter,
    sync: {
      imported: 3,
      skipped: 2,
      filesScanned: 4,
      errors: [],
    },
    summary: {
      totalRequests: 18,
      totalCostUsd: "0.387250",
      totalInputTokens: 48230,
      totalOutputTokens: 12680,
      totalCacheReadTokens: 39200,
      totalCacheCreationTokens: 0,
      totalReasoningOutputTokens: 5860,
      realTotalTokens: 100110,
      cacheHitRate: 39200 / (48230 + 39200),
    },
    trends: [
      {
        date: "2026-06-06",
        requestCount: 5,
        totalCostUsd: "0.082100",
        totalInputTokens: 12600,
        totalOutputTokens: 2800,
        totalCacheReadTokens: 9200,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 920,
        realTotalTokens: 24600,
      },
      {
        date: "2026-06-07",
        requestCount: 7,
        totalCostUsd: "0.163900",
        totalInputTokens: 18600,
        totalOutputTokens: 5200,
        totalCacheReadTokens: 15400,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 2380,
        realTotalTokens: 39200,
      },
      {
        date: "2026-06-08",
        requestCount: 6,
        totalCostUsd: "0.141250",
        totalInputTokens: 17030,
        totalOutputTokens: 4680,
        totalCacheReadTokens: 14600,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 2560,
        realTotalTokens: 36310,
      },
    ],
    modelBreakdown: [
      {
        name: "gpt-5.4",
        requestCount: 12,
        totalCostUsd: "0.301300",
        totalInputTokens: 34200,
        totalOutputTokens: 9820,
        totalCacheReadTokens: 28800,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 4720,
        realTotalTokens: 72820,
      },
      {
        name: "gpt-5.4-mini",
        requestCount: 6,
        totalCostUsd: "0.085950",
        totalInputTokens: 14030,
        totalOutputTokens: 2860,
        totalCacheReadTokens: 10400,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 1140,
        realTotalTokens: 27290,
      },
    ],
    effortBreakdown: [
      {
        name: "high",
        requestCount: 9,
        totalCostUsd: "0.268400",
        totalInputTokens: 27600,
        totalOutputTokens: 8360,
        totalCacheReadTokens: 21400,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 4620,
        realTotalTokens: 57360,
      },
      {
        name: "medium",
        requestCount: 9,
        totalCostUsd: "0.118850",
        totalInputTokens: 20630,
        totalOutputTokens: 4320,
        totalCacheReadTokens: 17800,
        totalCacheCreationTokens: 0,
        totalReasoningOutputTokens: 1240,
        realTotalTokens: 42750,
      },
    ],
    availableModels: ["gpt-5.4", "gpt-5.4-mini"],
    availableEfforts: ["high", "medium"],
    logs: [
      {
        requestId: "codex_session:preview-a:3",
        sessionId: "preview-a",
        model: "gpt-5.4",
        provider: "openai",
        effort: "high",
        createdAt: updatedAt,
        inputTokens: 2250,
        outputTokens: 760,
        cacheReadTokens: 1800,
        cacheCreationTokens: 0,
        reasoningOutputTokens: 420,
        totalCostUsd: "0.017475",
        sourcePath: "/Users/example/.codex/sessions/2026/06/08/rollout-preview-a.jsonl",
      },
      {
        requestId: "codex_session:preview-b:2",
        sessionId: "preview-b",
        model: "gpt-5.4-mini",
        provider: "openai",
        effort: "medium",
        createdAt: "2026-06-08T08:12:00Z",
        inputTokens: 1680,
        outputTokens: 520,
        cacheReadTokens: 980,
        cacheCreationTokens: 0,
        reasoningOutputTokens: 180,
        totalCostUsd: "0.004335",
        sourcePath: "/Users/example/.codex/sessions/2026/06/08/rollout-preview-b.jsonl",
      },
    ],
  };
}
